// main block begin
// generated by mkuse/c2any [/home/gzleo/aprog/mkuse/c2any/c2any -dst vlang -hdr /opt/vcpkg/installed/x64-linux-dynamic/include/reproc/reproc.h -pkg psutil -out . -genwrap1 -genclass -trimpfxs reproc_,REPROC_]
@[translated] module psutil


#include <reproc/reproc.h>

// todo // pub const STOP_ACTIONS_NULL = (reproc_stop_actions) {                         { REPROC_STOP_NOOP, 0 },                                                       { REPROC_STOP_NOOP, 0 },                                                       { REPROC_STOP_NOOP, 0 },                                                     } // heheh

// struct reproc_t C.
pub struct C.reproc_t {
pub mut:
}

// struct reproc_t C.
// pub type reproc_t = C.reproc_t // Elaborated

// struct REPROC_STREAM C.
// pub type REPROC_STREAM = C.REPROC_STREAM // Elaborated

// struct REPROC_REDIRECT C.
// pub type REPROC_REDIRECT = C.REPROC_REDIRECT // Elaborated

// struct REPROC_STOP C.
 //pub type REPROC_STOP = C.REPROC_STOP // Elaborated

// struct reproc_stop_action C.
pub struct C.reproc_stop_action {
pub mut:
    action i32  	// 0: 4: REPROC_STOP
    timeout int32  	// 1: 4: int
}

// struct reproc_stop_action C.
 pub type reproc_stop_action = C.reproc_stop_action // Elaborated

// struct reproc_stop_action C.
pub struct C.reproc_stop_action {
pub mut:
    action i32  	// 0: 4: REPROC_STOP
    timeout int32  	// 1: 4: int
}

// struct reproc_stop_actions C.
pub struct C.reproc_stop_actions {
pub mut:
    first reproc_stop_action  	// 0: 8: reproc_stop_action
    second reproc_stop_action  	// 1: 8: reproc_stop_action
    third reproc_stop_action  	// 2: 8: reproc_stop_action
}

// struct reproc_stop_actions C.
 pub type reproc_stop_actions = C.reproc_stop_actions // Elaborated

// struct reproc_stop_actions C.
pub struct C.reproc_stop_actions {
pub mut:
    first reproc_stop_action  	// 0: 8: reproc_stop_action
    second reproc_stop_action  	// 1: 8: reproc_stop_action
    third reproc_stop_action  	// 2: 8: reproc_stop_action
}

// struct reproc_handle C.
// pub type reproc_handle = C.reproc_handle // Int

// struct reproc_redirect C.
pub struct C.reproc_redirect {
pub mut:
    type i32  	// 0: 4: REPROC_REDIRECT
    handle int32  	// 1: 4: reproc_handle
    // file &_IO_FILE = unsafe{nil} 	// 2: 8: FILE *
    path charptr  	// 3: 8: const char *
}

// struct reproc_redirect C.
 pub type reproc_redirect = C.reproc_redirect // Elaborated

// struct reproc_redirect C.
pub struct C.reproc_redirect {
pub mut:
    type i32  	// 0: 4: REPROC_REDIRECT
    handle int32  	// 1: 4: reproc_handle
  //  file &_IO_FILE = unsafe{nil} 	// 2: 8: FILE *
    path charptr  	// 3: 8: const char *
}

// struct REPROC_ENV C.
// pub type REPROC_ENV = C.REPROC_ENV // Elaborated


// struct reproc_event_source C.
pub struct C.reproc_event_source {
pub mut:
 //   process &reproc_t = unsafe{nil} 	// 0: 8: reproc_t *
    interests int32  	// 1: 4: int
    events int32  	// 2: 4: int
}

// struct reproc_event_source C.
 pub type reproc_event_source = C.reproc_event_source // Elaborated

// struct reproc_event_source C.
pub struct C.reproc_event_source {
pub mut:
   // process &reproc_t = unsafe{nil} 	// 0: 8: reproc_t *
    interests int32  	// 1: 4: int
    events int32  	// 2: 4: int
}

// type Reproc_options C.reproc_options // 270
@[typedef]
pub struct C.reproc_options{}
pub type Reproc_options = C.reproc_options


// int reproc_start(reproc_t *, const char *const *, reproc_options)
fn C.reproc_start(... voidptr) int32

// int reproc_start(reproc_t *, const char *const *, reproc_options)
/*
pub fn start(process voidptr, argv voidptr, options struct reproc_options) int32 {
  cret_ := C.reproc_start(process, argv, options)
  return cret_
}
*/

// int reproc_pid(reproc_t *)
fn C.reproc_pid(... voidptr) int32

// int reproc_pid(reproc_t *)
pub fn reproc_pid(process voidptr) int32 {
  cret_ := C.reproc_pid(process)
  return cret_
}


// int reproc_poll(reproc_event_source *, size_t, int)
fn C.reproc_poll(... voidptr) int32

// int reproc_poll(reproc_event_source *, size_t, int)
pub fn reproc_poll(sources voidptr, num_sources usize, timeout int32) int32 {
  cret_ := C.reproc_poll(sources, num_sources, timeout)
  return cret_
}


// type REPROC_STREAM C.REPROC_STREAM // 270
// @[typedef]
// pub struct C.REPROC_STREAM{}
// pub type REPROC_STREAM = C.REPROC_STREAM


// int reproc_read(reproc_t *, REPROC_STREAM, uint8_t *, size_t)
fn C.reproc_read(... voidptr) int32

// int reproc_read(reproc_t *, REPROC_STREAM, uint8_t *, size_t)
pub fn reproc_read(process voidptr, stream i32, buffer voidptr, size usize) int32 {
  cret_ := C.reproc_read(process, stream, buffer, size)
  return cret_
}


// int reproc_write(reproc_t *, const uint8_t *, size_t)
fn C.reproc_write(... voidptr) int32

// int reproc_write(reproc_t *, const uint8_t *, size_t)
pub fn reproc_write(process voidptr, buffer voidptr, size usize) int32 {
  cret_ := C.reproc_write(process, buffer, size)
  return cret_
}


// int reproc_close(reproc_t *, REPROC_STREAM)
fn C.reproc_close(... voidptr) int32

// int reproc_close(reproc_t *, REPROC_STREAM)
pub fn reproc_close(process voidptr, stream i32) int32 {
  cret_ := C.reproc_close(process, stream)
  return cret_
}


// int reproc_wait(reproc_t *, int)
fn C.reproc_wait(... voidptr) int32

// int reproc_wait(reproc_t *, int)
pub fn reproc_wait(process voidptr, timeout int32) int32 {
  cret_ := C.reproc_wait(process, timeout)
  return cret_
}


// int reproc_terminate(reproc_t *)
fn C.reproc_terminate(... voidptr) int32

// int reproc_terminate(reproc_t *)
pub fn reproc_terminate(process voidptr) int32 {
  cret_ := C.reproc_terminate(process)
  return cret_
}


// int reproc_kill(reproc_t *)
fn C.reproc_kill(... voidptr) int32

// int reproc_kill(reproc_t *)
pub fn reproc_kill(process voidptr) int32 {
  cret_ := C.reproc_kill(process)
  return cret_
}


// type Reproc_stop_actions C.reproc_stop_actions // 270
@[typedef]
pub struct C.reproc_stop_actions{}
pub type Reproc_stop_actions = C.reproc_stop_actions


// int reproc_stop(reproc_t *, reproc_stop_actions)
fn C.reproc_stop(... voidptr) int32

// int reproc_stop(reproc_t *, reproc_stop_actions)
/*
pub fn stop(process voidptr, stop struct reproc_stop_actions) int32 {
  cret_ := C.reproc_stop(process, stop)
  return cret_
}
*/

// const int * reproc_strerror(int)
fn C.reproc_strerror(... voidptr) voidptr

// const int * reproc_strerror(int)
pub fn reproc_strerror(error int32) voidptr {
  cret_ := C.reproc_strerror(error)
  return cret_
}

// main block end
